<?php
/**
 * PM_PageSpeedReport
 *
 * Builds HTML output for PageSpeed Insights results:
 *   - build()                 → standalone Google Doc with full audit detail
 *   - build_dashboard_html()  → WP Admin dashboard summary panel
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class PM_PageSpeedReport {

    // ── Google Doc ────────────────────────────────────────────────────────────

    /**
     * Build a full PageSpeed Insights HTML document for upload to Google Drive.
     *
     * @param array  $data         Full data from PM_PageSpeed::run_full().
     * @param string $client_name
     * @return string  HTML string.
     */
    public static function build( array $data, $client_name ) {
        $html  = self::doc_styles();
        $html .= "<body>\n";
        $html .= "<h1>PageSpeed Insights Report &mdash; " . esc_html( $client_name ) . "</h1>\n";
        $html .= "<p class='meta'>URL: <strong>" . esc_html( $data['url'] ) . "</strong>"
               . " &nbsp;|&nbsp; Date: <strong>" . date( 'F j, Y', $data['timestamp'] ) . "</strong></p>\n";

        // ── Scores overview ───────────────────────────────────────────────────
        $html .= "<h2>Scores Overview</h2>\n";
        $html .= "<table>\n";
        $html .= "<tr><th>Category</th><th>📱 Mobile</th><th>🖥 Desktop</th></tr>\n";

        foreach ( $data['categories'] as $cat_key => $cat ) {
            $m = $data['scores']['mobile'][ $cat_key ]  ?? null;
            $d = $data['scores']['desktop'][ $cat_key ] ?? null;
            $html .= "<tr><td><strong>" . esc_html( $cat['title'] ) . "</strong></td>"
                   . "<td>" . self::score_cell( $m ) . "</td>"
                   . "<td>" . self::score_cell( $d ) . "</td></tr>\n";
        }
        $html .= "</table>\n";

        // ── Category detail ───────────────────────────────────────────────────
        foreach ( $data['categories'] as $cat_key => $category ) {
            $html .= "<h2>" . esc_html( $category['title'] ) . "</h2>\n";

            foreach ( [ 'mobile' => '📱 Mobile', 'desktop' => '🖥 Desktop' ] as $strategy => $label ) {
                $audits = $category['audits'][ $strategy ] ?? null;
                if ( ! $audits ) continue;

                $cat_score = $data['scores'][ $strategy ][ $cat_key ] ?? null;
                $html .= "<h3>{$label}" . ( $cat_score !== null ? " &nbsp;<span style='color:" . self::score_color( $cat_score ) . ";'>{$cat_score}/100</span>" : '' ) . "</h3>\n";

                // Errors
                if ( ! empty( $audits['errors'] ) ) {
                    $count = count( $audits['errors'] );
                    $html .= "<h4 style='color:#c62828;'>&#10060; Failed Audits ({$count})</h4>\n";
                    $html .= self::audit_table( $audits['errors'], 'error' );
                }

                // Opportunities
                if ( ! empty( $audits['opportunities'] ) ) {
                    $count = count( $audits['opportunities'] );
                    $html .= "<h4 style='color:#c87820;'>&#128161; Opportunities ({$count})</h4>\n";
                    $html .= self::audit_table( $audits['opportunities'], 'opportunity' );
                }

                // Warnings
                if ( ! empty( $audits['warnings'] ) ) {
                    $count = count( $audits['warnings'] );
                    $html .= "<h4 style='color:#c87820;'>&#9888; Warnings ({$count})</h4>\n";
                    $html .= self::audit_table( $audits['warnings'], 'warning' );
                }

                // Diagnostics
                if ( ! empty( $audits['diagnostics'] ) ) {
                    $count = count( $audits['diagnostics'] );
                    $html .= "<h4 style='color:#1565c0;'>&#8505; Diagnostics ({$count})</h4>\n";
                    $html .= self::audit_table( $audits['diagnostics'], 'diagnostic' );
                }

                // Passed
                if ( ! empty( $audits['passed'] ) ) {
                    $count  = count( $audits['passed'] );
                    $titles = implode( ', ', array_map(
                        fn( $a ) => esc_html( $a['title'] ),
                        $audits['passed']
                    ) );
                    $html .= "<h4 style='color:#2e7d32;'>&#10003; Passed ({$count})</h4>\n";
                    $html .= "<p style='color:#555; font-size:10pt;'>{$titles}</p>\n";
                }

                if ( empty( $audits['errors'] ) && empty( $audits['opportunities'] )
                  && empty( $audits['warnings'] ) && empty( $audits['diagnostics'] ) ) {
                    $html .= "<p style='color:#2e7d32;'>&#10003; All audits passed for this category.</p>\n";
                }
            }
        }

        $html .= "<p class='footer'>Generated by MPWR Maintenance &mdash; " . date( 'Y-m-d H:i:s' ) . "</p>\n";
        $html .= "</body></html>";

        return $html;
    }

    // ── Dashboard summary HTML ────────────────────────────────────────────────

    /**
     * Build the HTML panel shown in WP Admin after an on-demand PageSpeed test.
     *
     * @param array      $full_data  From PM_PageSpeed::run_full().
     * @param array|null $previous   Previously stored scores for comparison.
     * @param string     $doc_url    Optional Drive link to the full report.
     * @return string
     */
    public static function build_dashboard_html( array $full_data, $previous = null, $doc_url = '' ) {
        $scores = $full_data['scores'];
        $html   = '<strong>&#10003; PageSpeed test complete</strong>';
        $html  .= '<p style="color:#555;font-size:11px;margin:4px 0 14px;">Tested: ' . esc_html( $full_data['url'] ) . '</p>';

        // ── Scores table ──────────────────────────────────────────────────────
        $th = 'style="background:#1a3a5c;color:#fff;padding:5px 10px;font-size:11px;text-align:center;"';
        $th_l = 'style="background:#1a3a5c;color:#fff;padding:5px 10px;font-size:11px;text-align:left;"';
        $html .= '<table style="width:100%;border-collapse:collapse;margin-bottom:16px;font-size:12px;">';
        $html .= "<tr><th {$th_l}>Category</th>";
        $html .= "<th {$th}>📱 Mobile</th>";
        if ( $previous ) $html .= "<th {$th}>Prev</th>";
        $html .= "<th {$th}>🖥 Desktop</th>";
        if ( $previous ) $html .= "<th {$th}>Prev</th>";
        $html .= '</tr>';

        $cat_labels = [
            'performance'   => 'Performance',
            'accessibility' => 'Accessibility',
            'best_practices'=> 'Best Practices',
            'seo'           => 'SEO',
        ];
        foreach ( $cat_labels as $key => $label ) {
            $m  = $scores['mobile'][ $key ]  ?? null;
            $d  = $scores['desktop'][ $key ] ?? null;
            $pm = $previous['scores']['mobile'][ $key ]  ?? null;
            $pd = $previous['scores']['desktop'][ $key ] ?? null;

            $td = 'style="padding:4px 8px;border-bottom:1px solid #eee;"';
            $html .= "<tr>";
            $html .= "<td {$td}>{$label}</td>";
            $html .= '<td style="padding:4px 8px;border-bottom:1px solid #eee;text-align:center;font-weight:700;color:' . self::score_color( $m ) . ';">' . ( $m ?? '—' ) . '</td>';
            if ( $previous ) $html .= '<td style="padding:4px 8px;border-bottom:1px solid #eee;text-align:center;font-size:11px;color:#999;">' . ( $pm ?? '—' ) . self::change_badge( $pm, $m ) . '</td>';
            $html .= '<td style="padding:4px 8px;border-bottom:1px solid #eee;text-align:center;font-weight:700;color:' . self::score_color( $d ) . ';">' . ( $d ?? '—' ) . '</td>';
            if ( $previous ) $html .= '<td style="padding:4px 8px;border-bottom:1px solid #eee;text-align:center;font-size:11px;color:#999;">' . ( $pd ?? '—' ) . self::change_badge( $pd, $d ) . '</td>';
            $html .= '</tr>';
        }
        $html .= '</table>';

        // ── Issues per category ───────────────────────────────────────────────
        foreach ( $full_data['categories'] as $cat_key => $category ) {
            $m_audits = $category['audits']['mobile'] ?? [];
            $errors   = $m_audits['errors']        ?? [];
            $opps     = $m_audits['opportunities']  ?? [];
            $warnings = $m_audits['warnings']       ?? [];

            if ( empty( $errors ) && empty( $opps ) && empty( $warnings ) ) {
                continue;
            }

            $html .= '<div style="margin-bottom:14px;">';
            $html .= '<strong style="font-size:12px;display:block;margin-bottom:6px;color:#1a3a5c;">'
                   . esc_html( $category['title'] ) . ' — Mobile</strong>';

            foreach ( $errors as $a ) {
                $val = $a['displayValue'] ? ' <span style="color:#777;">— ' . esc_html( $a['displayValue'] ) . '</span>' : '';
                $html .= '<div style="font-size:11px;padding:2px 0;color:#c62828;">&#10060; <strong>' . esc_html( $a['title'] ) . "</strong>{$val}</div>";
            }
            foreach ( $opps as $a ) {
                $savings = $a['savings_ms'] ? ' <span style="color:#777;">— save ~' . round( $a['savings_ms'] / 1000, 1 ) . 's</span>' : '';
                $html .= '<div style="font-size:11px;padding:2px 0;color:#c87820;">&#128161; <strong>' . esc_html( $a['title'] ) . "</strong>{$savings}</div>";
            }
            foreach ( $warnings as $a ) {
                $val = $a['displayValue'] ? ' <span style="color:#777;">— ' . esc_html( $a['displayValue'] ) . '</span>' : '';
                $html .= '<div style="font-size:11px;padding:2px 0;color:#888;">&#9888; <strong>' . esc_html( $a['title'] ) . "</strong>{$val}</div>";
            }

            $html .= '</div>';
        }

        if ( $doc_url ) {
            $html .= '<p style="margin-top:10px;font-size:12px;">&#128196; <a href="' . esc_url( $doc_url ) . '" target="_blank">View full PageSpeed report with fixes in Google Drive &rarr;</a></p>';
        }

        return $html;
    }

    // ── Shared helpers ────────────────────────────────────────────────────────

    private static function audit_table( array $audits, $type ) {
        $is_opp = $type === 'opportunity';
        $td     = 'style="padding:5px 8px;border-bottom:1px solid #e0e0e0;font-size:10pt;vertical-align:top;"';
        $th     = 'style="background:#1a3a5c;color:#fff;padding:5px 8px;font-size:10pt;text-align:left;"';

        $html  = "<table>\n<tr>";
        $html .= "<th {$th}>Issue</th>";
        $html .= $is_opp ? "<th {$th}>Est. Savings</th>" : "<th {$th}>Score</th>";
        $html .= "<th {$th}>Current Value</th>";
        $html .= "<th {$th}>Recommended Fix</th>";
        $html .= "</tr>\n";

        foreach ( $audits as $a ) {
            $score_cell = $a['score'] !== null ? self::score_cell( $a['score'] ) : '&mdash;';

            if ( $is_opp ) {
                if ( $a['savings_ms'] ) {
                    $savings = round( $a['savings_ms'] / 1000, 1 ) . 's';
                } elseif ( $a['savings_bytes'] ) {
                    $savings = round( $a['savings_bytes'] / 1024 ) . ' KB';
                } else {
                    $savings = '&mdash;';
                }
            }

            $html .= "<tr>";
            $html .= "<td {$td}><strong>" . esc_html( $a['title'] ) . "</strong></td>";
            $html .= $is_opp
                ? "<td {$td}>{$savings}</td>"
                : "<td {$td}>{$score_cell}</td>";
            $html .= "<td {$td}>" . esc_html( $a['displayValue'] ) . "</td>";
            $html .= "<td {$td} style='font-size:9pt;color:#555;padding:5px 8px;border-bottom:1px solid #e0e0e0;vertical-align:top;'>"
                   . esc_html( $a['description'] ) . "</td>";
            $html .= "</tr>\n";
        }

        return $html . "</table>\n";
    }

    public static function score_cell( $score ) {
        if ( $score === null ) return '&mdash;';
        $color = self::score_color( $score );
        $label = $score >= 90 ? 'Good' : ( $score >= 50 ? 'Needs Improvement' : 'Poor' );
        return "<strong style='color:{$color}'>{$score}</strong> <span style='font-size:9pt;color:{$color};'>({$label})</span>";
    }

    public static function score_color( $score ) {
        if ( $score === null ) return '#999';
        if ( $score >= 90 )   return '#2e7d32';
        if ( $score >= 50 )   return '#c87820';
        return '#c62828';
    }

    private static function change_badge( $old, $new ) {
        if ( $old === null || $new === null ) return '';
        $diff = $new - $old;
        if ( $diff > 0 ) return ' <span style="color:#2e7d32;">&#9650;+' . $diff . '</span>';
        if ( $diff < 0 ) return ' <span style="color:#c62828;">&#9660;' . $diff . '</span>';
        return '';
    }

    // ── Styles ────────────────────────────────────────────────────────────────

    private static function doc_styles() {
        return <<<HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body  { font-family: Arial, sans-serif; font-size: 11pt; color: #222; }
  h1    { font-size: 18pt; color: #1a3a5c; border-bottom: 2px solid #1a3a5c; padding-bottom: 6px; }
  h2    { font-size: 14pt; color: #1a3a5c; margin-top: 28px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  h3    { font-size: 12pt; color: #2e4a6a; margin-top: 18px; }
  h4    { font-size: 11pt; margin-top: 12px; margin-bottom: 6px; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 14px; }
  th    { text-align: left; padding: 5px 8px; }
  td    { padding: 5px 8px; border-bottom: 1px solid #e0e0e0; vertical-align: top; }
  tr:nth-child(even) td { background: #f7f9fc; }
  .meta   { color: #555; font-size: 10pt; margin-bottom: 20px; }
  .footer { color: #999; font-size: 9pt; margin-top: 32px; border-top: 1px solid #eee; padding-top: 8px; }
</style>
</head>

HTML;
    }
}
